[deps]
AbstractDifferentiation = "c29ec348-61ec-40c8-8164-b8c60e9d9f3d"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Diffractor = "9f5e2b26-1114-432f-b630-d3fe2085c51c"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MUMPS = "55d2b088-9f4e-11e9-26c0-150b02ea6a46"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MathOptSymbolicAD = "309f4015-3481-4d63-a8f9-aeb13adfe8eb"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Remez = "2e7db186-766a-50e7-8928-5c30181fb135"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
SparsityDetection = "684fba80-ace3-11e9-3d08-3bc7ed6f96df"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatProfilerHTML = "a8a75453-ed82-57c9-9e16-4cd1196ecbf5"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
UpdateJulia = "770da0de-323d-4d28-9202-0e205c1e0aff"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"
